### ISSUE TITLE
当前在B站的直播存在1-2分钟延迟

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/community#1]
## 问题描述

当前在B站的直播存在1-2分钟延迟

## 问题分析

1. 根据当前个人对于直播的认知，主播和观看者的时延不应当低于5-10s
2. 当前主播时延比较长的问题，可能存在俩问题：
a. 使用的录制工具不是obs
b. 直播账号需要开白

## 解决办法

**Comment by rootsongjc** [comment]
该 issue 已分分配给 @Miss-you

**Comment by Miss-you** [comment]
进展同步，周日的时候由于需要上传身份证才能验证搁置了几天，今天已经上传身份证，预计端午节可以验证ok
![image](https://user-images.githubusercontent.com/3816205/85423023-cb68d600-b5a8-11ea-97a2-20f8ed6c652a.png)

**Comment by rootsongjc** [comment]
一般情况下延迟都在 1 分钟以内，可能是几十秒。

**Comment by Miss-you** [comment]
> 一般情况下延迟都在 1 分钟以内，可能是几十秒。

根据个人使用经验，良性互动的直播时延应该低于1-5秒，这样的时延有些不可接受。

1、时延有点高
2、观众多的时候可能时延也会变高，可能要评估下后者的影响

**Comment by rootsongjc** [comment]
我想可以这样：互动是为了让观者更好的了解某件事，比如对某个观点的看法，而这个观点不影响播主的后续行为，或者播主可以在后续对观众的行为作出评判，而不用实时的与观众互动。

**Comment by Miss-you** [comment]
![image](https://user-images.githubusercontent.com/3816205/85705692-0c312e00-b714-11ea-998d-20642e52f893.png)
今天我尝试了一下，时延差不多在10秒-20秒左右
我去找下b站直播的人问下

**Comment by Miss-you** [comment]
有个降低时延的办法，等大家都加入后，断开推流重新推流，让大家刷新下页面可以把延迟降到很低
![image](https://user-images.githubusercontent.com/3816205/85706660-012acd80-b715-11ea-9fab-5e7aa697e25e.png)

**Comment by Miss-you** [comment]
刷新页面后，时延骤增
![image](https://user-images.githubusercontent.com/3816205/85706739-169ff780-b715-11ea-9e14-21963929764d.png)

**Comment by Miss-you** [comment]
测试总结：
1、如果不使用一些优化手段，直播间默认时延在20-30秒左右，体验上还是比较影响交互的
2、电脑直播延迟在10-30秒延迟，手机延迟在20-30秒
3、bilibili直播服务器架设在上海，推流点和测试直播点均在深圳

优化办法：
1、b站，跟进中
2、待大家都加入后，断开推流重新推流，让大家刷新下页面，基本时延可以在10s以内
3、观看者如果发现时延较高，可以通过调整分流（主、备用123等）以及直播页面的刷新按钮刷新页面，尝试降低时延
![image](https://user-images.githubusercontent.com/3816205/85712242-b613b900-b71a-11ea-8723-d1b8236f1ad4.png)

问答交互建议：
1、有一个旁观者，实时总结老师讲的重点（可以提前列好），然后在聊天栏刷新当前分享人讲的进度
2、如果需要QA环节的话，则建议分享者先等待30秒-60秒，给大家一个缓冲时间思考问题以及等待时间不一致的人，要求大家一并将问题发到留言栏，提问者通过打字提问，再随机选或者精选几个问题进行回答
3、极客时间有一个tgo直播，能否试试他们的，他们的时延会不会更低些？毕竟游戏直播往往有时延
![image](https://user-images.githubusercontent.com/3816205/85709213-a0e95b00-b717-11ea-9fd9-e12874724a01.png)

**Comment by rootsongjc** [comment]
B 站直播我使用过的体验还是可以的，单人直播的话延迟是可以接受的。但是我们这个如果是使用 zoom 多人连线再直播，这个不稳定因素就太高了，在推流时的 OBS 应该也可以优化下以减少带宽占用。

**Comment by Miss-you** [comment]
zoom多人连线跟obs直播抢占的应该是带宽以及显卡。
尽量选择显卡好（比如我的是1080），带宽大（200M起），且在上海的人做主持人是不是就解决这个问题了？
还是说，因为要连接zoom，需要开vpn，这样直播推流的话也需要开启vpn是么？

**Comment by Miss-you** [comment]
我觉得，直播的时候，多人连线选择腾讯会议比较好。这样就不需要同时一边开vpn一边直播了，这样时延可控。

**Comment by Miss-you** [comment]
联席会议这种参加人数不多，我理解腾讯会议可以搞定
腾讯会议胜在不需要开vpn
最大的缺点是，腾讯会议不支持录屏

**Comment by Miss-you** [comment]
刚刚验证了下“先加入zoom会议，然后断开vpn开始直播分享”方案是否可行。

初步验证结果如下：
![image](https://user-images.githubusercontent.com/3816205/85926476-4fd19680-b8d2-11ea-8255-15d8d067aeee.png)
zoom一旦断开vpn，就基本不可用了

结论：
建议分享时采用腾讯会议主持会议，再通过bilibili直播进行分享

**Comment by rootsongjc** [comment]
代理可以设置规则的，可以设置推流不走代理，目前看推流是正常的，基本不会丢帧，上次多人会议直播的时候zoom 也比较稳定，没有卡顿和掉线的情况发生，今后我们基本不会做2 人以上的会议直播，一般有个主持人，有个演讲者就可以了。

**Comment by Miss-you** [comment]
> 代理可以设置规则的，可以设置推流不走代理，目前看推流是正常的，基本不会丢帧，上次多人会议直播的时候zoom 也比较稳定，没有卡顿和掉线的情况发生，今后我们基本不会做2 人以上的会议直播，一般有个主持人，有个演讲者就可以了。

这个操作我没有试过，有教程么？我觉得应该有很多人不会配置，我也研究下如何配置

**Comment by rootsongjc** [comment]
主要是推流的电脑需要保证网速和运行速度，最好不要运行其他应用，专门用来推流。我们下次再使用两台电脑来试一试。

**Comment by Miss-you** [comment]
> 主要是推流的电脑需要保证网速和运行速度，最好不要运行其他应用，专门用来推流。我们下次再使用两台电脑来试一试。

周末试下，我其实就有两台，可以直接验证。验证zoom的时候比较麻烦。

**Comment by Miss-you** [comment]
1、直播这里差最后一点，用哪个工具可以分流？是vpn的一个配置是么？我当前vpn的配置是全部流量走vpn
该怎么办？
主持人开直播，嘉宾zoom分享

2、分享时间是定在工作日晚上还是周末晚上？
比如上次直播分享的时候是6.17日，刚好是周二，那时候我在上班，我的笔记本带不动直播，我是无法当主持人的
主持人需要电脑比较好而且带宽大

3、zoom付费账号什么时候买？
再不买的话是不是先用腾讯会议？

**Comment by Miss-you** [comment]
主持人开直播，嘉宾zoom分享

**Comment by rootsongjc** [comment]
1. 我在参加 Zoom 会议的同时使用OBS推流的时候实际发现并没有丢帧，VPN 也不需要特别的配置，我觉得还是与 B 站本身的延迟有关。
2. 我觉得最好是工作日晚上，周末晚上加可能就没那么多动力去学习了。
3. zoom 付费账号我们按年买的话需要$119.92，这个钱需要确认如何支付，我建议继续使用 zoom，反正迟早要买

**Comment by Miss-you** [comment]
> 1. 我在参加 Zoom 会议的同时使用OBS推流的时候实际发现并没有丢帧，VPN 也不需要特别的配置，我觉得还是与 B 站本身的延迟有关。
> 2. 我觉得最好是工作日晚上，周末晚上加可能就没那么多动力去学习了。
> 3. zoom 付费账号我们按年买的话需要$119.92，这个钱需要确认如何支付，我建议继续使用 zoom，反正迟早要买

第一个不太认同，上周开会的时候，你同时开了直播，基本卡住了
第二个和第三个周会敲定下吧

**Comment by Miss-you** [comment]
第二个问题，由嘉宾的时间来确定
第三个问题，先使用腾讯会议

**Comment by rootsongjc** [comment]
我开直播的时候 OBS 并没有卡住，推流显示没有丢帧，我觉得应该是在 B 站那边问题。
7 月 11 日晚上我购买了 Zoom 基本套餐，以后会议时不会有限时 40 分钟的问题了。

**Comment by rootsongjc** [comment]
我觉得这个是直播过程中难以避免的，尽量不要在直播过程中实时跟观众互动，可以通过那种允许有时间差的，或者约定一个固定时间统一答疑之类的方式。
