### ISSUE TITLE
当前Cloud Native线上虚拟峰会主页中的合作伙伴栏缺少云原生社区

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/community#11]
问题描述：

当前云原生社区跟CNCF有合作，会作为Cloud Native合作伙伴，在Cloud Native官网https://cncf.lfasiallc.cn/#也应该会有展示。

但点开网站后，合作伙伴这里缺少云原生社区的图标，需要跟进下。（当前该活动的一些其他准备活动也需要跟进）

![image](https://user-images.githubusercontent.com/3816205/85983881-dabda880-ba1a-11ea-8948-47599db13888.png)

**Comment by rootsongjc** [comment]
这个 @Matthew-Dong 正在跟进。

**Comment by Matthew-Dong** [comment]
已和 CNCF 侧交流，计划于 7/6 更新

**Comment by Miss-you** [comment]
done

**Comment by Miss-you** [comment]
![image](https://user-images.githubusercontent.com/3816205/87170810-6d582480-c304-11ea-9d02-c6dbc40aa362.png)
已经增加

**Comment by rootsongjc** [comment]
同时再公告下，今日云原生社区成为了[CSDI Summit（中国软件研发管理行业技术峰会）](https://www.bagevent.com/event/csdisummit/p/415759)的媒体合作伙伴。
![image](https://user-images.githubusercontent.com/3328185/87214608-c0f85b80-c360-11ea-97b5-c60cc69c78c8.png)
