### ISSUE TITLE
将所有 GitHub Project 的看板合并到 Global 看板里

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#17]
当前社区的 GitHub 看板过多过于分散，有 Website、Volunteer、Global 这三个，建议统一成一个看板，都放到 Global 里即可，这样会省去在不同看板中来回跳转的麻烦，我们的事务也不至于多到要分成那么多看板来管理。@lonng

**Comment by lonng** [comment]
可以，我调整一下

**Comment by lonng** [comment]
Done
