### ISSUE TITLE
【读书小组招募】《Programming Kubernetes》/《Kubernetes 源码剖析》读书小组招募

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/community#19]
IT技术日新月异，想必每个IT人都会有类似的焦虑：我该学习什么？哪些知识学到就是赚到？怎样学习才是最有效的？

[
以下略过3000字软文
……
]

## 学习方法

![image](https://user-images.githubusercontent.com/3816205/86516315-2674b580-be52-11ea-8490-0fbf39a0390f.png)

## 为什么要读《Programming Kubernetes》

学习技巧是类似的，通常分为学什么，分类，读书技巧和理解技巧四部分。而读书小组一开始就帮你解决了学什么和知识分类的问题：以Kubernetes的风格去编写程序，是云原生开发工程师的基本技能；而《Programming Kubernetes》又恰是这个领域的比较经典的一本书，属于第一第二手资源，值得学习。

[TODO，待补充，小组做什么？]

- 多个人一起学习交流，互相督促，利用西蒙学习法，集中在1-2个月内钻研Kubernetes编程；一个人经常学不动啊……
![image](https://user-images.githubusercontent.com/3816205/86516733-a81a1280-be55-11ea-9674-3dd7dd4c3c46.png)

- 每周轮流组织分享，以教为学
![image](https://user-images.githubusercontent.com/3816205/86516616-bca9db00-be54-11ea-9fc5-56e9194f0a17.png)
- 免费，真的不收费；也不需要分享转载朋友圈……
![image](https://user-images.githubusercontent.com/3816205/86516631-e236e480-be54-11ea-8a58-11e363cfd0e3.png)

当前我们也会不仅仅局限于《Programming Kubernetes》这本书，常见operator框架的handbook、Kubernetes部分原理和源码也会有所涉及

## 适合人群

云原生初学者

## 预计周期
1.5-2个月学习周期

## 英文版电子书下载：
[Programming.Kubernetes](https://github.com/cloudnativeto/cloudnative.to/files/4857064/Programming.Kubernetes.pdf)

## 中文版获取方法
待补充

## 公众号
![image](https://user-images.githubusercontent.com/3816205/86516549-19f15c80-be54-11ea-8f6e-90f4939c763d.png)

## 其他

觉得我说的不错的求个github关注
![image](https://user-images.githubusercontent.com/3816205/86516898-1e6b4480-be57-11ea-95b1-2d19a7f3cc01.png)

> 活动面向全体云原生社区粉丝

**Comment by hzliangbin** [comment]
期待ing

**Comment by Miss-you** [comment]
读书会的事情
a. 《programming kubernetes》中文版转载申请。进展：已经申请通过，待生成pdf
b. 初期投票的人待拉群
c. 考虑到参与人的Kubernetes知识水平不同，会在开始之前做一次问卷调查。进展：问卷调查的设计
d. 读书小组宣传软文编写（need help）。
e. 根据最终选择结果邀请合适的嘉宾进行分享。已经邀请郑东旭大佬作首次分享，但需要跟他确定具体主题以及时间，我们这边也需要准备宣传事宜


产出：
1. 分享视频，参考围炉夜话
2. Kubernetes源码图解
3. 干货文章
4. 提升大家参与度

**Comment by zackzhangkai** [comment]
报个名，已经买了郑东旭大佬的书，求拉群

**Comment by rootsongjc** [comment]
可以先考虑这两个产出：
1. 第一次直播视频
2. Kubernetes 源码图解（可独立输出）

**Comment by Miss-you** [comment]
md导出pdf方法：
用Markdown来写自由书籍-开源技术的方案
https://www.ituring.com.cn/article/828

**Comment by Miss-you** [comment]
【腾讯文档】programming kubernetes 中文版，仅供阅览
https://docs.qq.com/pdf/DR1hha25Qa0ZDT2pK
先放在腾讯文档了，这几天再传到googledoc，或者有没有人帮忙弄下？

**Comment by rootsongjc** [comment]
有一个地方放就行了，@Miss-you 没必要传两遍了，腾讯文档体验也挺好的，还不需要翻墙，就用它吧。但是仅开放给云原生社区成员浏览。需要有个方式登记下所有浏览人员。

**Comment by erdun** [comment]
可以考虑为：
学习只是一方面，主要为产出高质量传播，助力云原生的传播，帮助中国云原生提高开发群体的质量
可以先建一个群体自己调式研究，写文章，群体内审核孵化，文章没有问题了，bilibili直播讲解，最后发布到云原生官网

**Comment by apigateway-demo** [comment]
https://github.com/talkgo/night

**Comment by rootsongjc** [comment]
> 可以考虑为：
> 学习只是一方面，主要为产出高质量传播，助力云原生的传播，帮助中国云原生提高开发群体的质量
> 可以先建一个群体自己调式研究，写文章，群体内审核孵化，文章没有问题了，bilibili直播讲解，最后发布到云原生官网

确实，不光是社区内学习，还需要把我们的成果传播出去才是。

**Comment by Miss-you** [comment]
> 可以考虑为：
> 学习只是一方面，主要为产出高质量传播，助力云原生的传播，帮助中国云原生提高开发群体的质量
> 可以先建一个群体自己调式研究，写文章，群体内审核孵化，文章没有问题了，bilibili直播讲解，最后发布到云原生官网

这个是不是应该属于学习后的事情？

**Comment by rootsongjc** [comment]
学习是个人的事情，社区主要起到组织推动的作用，过程中需要各位参与者的总结，活动完成后再梳理、发布、分享。

**Comment by lumincui** [comment]
想参与 programming kubernetes ，补充申请

**Comment by Miss-you** [comment]
> 想参与 programming kubernetes ，补充申请

最近没有哈，得下一期了

**Comment by rootsongjc** [comment]
这个是 Kubebuilder 的下一期。@vincenthcui

**Comment by lumincui** [comment]
是 Cloud Native Community 的子项目吗？ @Miss-you @rootsongjc

**Comment by rootsongjc** [comment]
@vincenthcui 是的，目前 @Miss-you 在组织中。

**Comment by Miss-you** [comment]
关闭啦，后面的活动会在项目跟踪：
https://github.com/cloudnativeto/sig-k8s-source-code

**Comment by liboyue23** [comment]
报个名，求拉群

**Comment by lumincui** [comment]
> 报个名，求拉群

@liboyue23 《Kubernetes 源码剖析》读书小组结束了哈

**Comment by zhaoweiguo** [comment]
> 报个名，求拉群

下一期很快就来了

**Comment by LuckyDogg** [comment]
现在还有么

**Comment by rootsongjc** [comment]
> 现在还有么

这个活动已经结束了。
