### ISSUE TITLE
目前社区志愿者组织看板的建议

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#2]
对于目前社区志愿者组织看板的建议：
1. 在 Community 仓库的 README 里增加志愿者分组及每个组的 lead
2. 为 issue 增加 label，关联到不同的志愿者分组

@lonng @yekangming

**Comment by lonng** [comment]
https://github.com/cloudnativeto/community/projects/2

**Comment by lonng** [comment]
Labels created.

**Comment by lonng** [comment]
PR 合并之后这个 Issue 就可以关闭了
