### ISSUE TITLE
[活动] kubebuilder 官方文档翻译

### ISSUE THREAD

**Issue by stevensu1977** [cloudnativeto/community#21]
kubebuilder 官方doc/book  :  https://book.kubebuilder.io/quick-start.html
计划翻译结果托管到CNC社区网站.

下面是开始翻以前的准备工作。
- [x] fork 仓库
- [x] 创建一个 docker 镜像用于编译官方文档
- [x] 设置 GitHub Action，发布 GitHub Pages
- [x] 编写翻译指南和规范
- [x] 开始招募译者
- [x] 开始翻译

**Comment by rootsongjc** [comment]
这个项目要分几个步骤来做：
1. 确认项目 Leader，大家可以自荐，或者推荐别人 @cloudnativeto/volunteer 
1. 初始化 github 仓库，使用Kubebuilder 官网仓库的模板，并配置 GitHub action 实现自动发布
1. 确认翻译认领和分工协作的方式，参考 http://servicemesher.com/istio-handbook
1. 正式开始认领，组织 review，并由 leader 监督完成

**Comment by zhaoweiguo** [comment]
现在leader确定了吗？

**Comment by rootsongjc** [comment]
@zhaoweiguo 还没有，欢迎自告奋勇来承担这份重任！

**Comment by hzliangbin** [comment]
@Miss-you 这个 kubebuilder 应该是已经翻译部分了吧. 推荐大佬牵头.

**Comment by rootsongjc** [comment]
推荐@Miss-you 来牵头吧

**Comment by majinghe** [comment]
已经开始翻译了吗？想作为一个参与者，翻译一下。

**Comment by rootsongjc** [comment]
还没开始呢

**Comment by jinrunsen** [comment]
@Miss-you @rootsongjc 带个头吧，报名参与翻译

**Comment by helight** [comment]
报名参与翻译

**Comment by rootsongjc** [comment]
目前 @lhb008 正在调试使用 github 发布，仓库已经 fork 过来了。https://github.com/cloudnativeto/kubebuilder
等调试完成就可以开始了。

**Comment by rootsongjc** [comment]
通过 https://github.com/cloudnativeto/kubebuilder/pull/1 Kubebuilder 官方文档已成功发布到社区官网：https://cloudnative.to/kubebuilder/

**Comment by Miss-you** [comment]
我时间有限，做不了牵头，最近事情太多了，我可以协助，希望有人自告奋勇牵头……

**Comment by rootsongjc** [comment]
这个活动将由 @lhb008 来牵头，issue 已经 assign 给他了。

**Comment by luffyao** [comment]
我也报个名

**Comment by DSqiansun** [comment]
@lhb008 已经开始了吗？ 我也报个名

**Comment by majinghe** [comment]
@Luffy110 可以加我的微信，majinghe11。如果你是云原生社区成员。我拉你进群。

**Comment by majinghe** [comment]
@DSqiansun 可以加我的微信，majinghe11。如果你是云原生社区成员。我拉你进群。

**Comment by majinghe** [comment]
Kubebuilder 翻译进度:

- [x] fork 仓库
- [x] 创建一个 docker 镜像用于编译官方文档
- [x] 设置 GitHub Action，发布 GitHub Pages
- [x] 编写翻译指南和规范
- [x] 开始招募译者
- [x] 开始翻译

**Comment by rootsongjc** [comment]
计划一周翻译一章，第一章 @Miss-you 已翻译完成，正在 Review。

**Comment by rootsongjc** [comment]
活动已经在有条不紊的进行中了。
- 了解详情见：https://github.com/cloudnativeto/kubebuilder 
- 查看中文文档见：https://cloudnative.to/kubebuilder

**Comment by majinghe** [comment]
第一章节已翻译完成，并合入 `zh` 分支，第二章、第三章 40%的已经翻译完毕，并合入 `zh` 分支，其余的处于 `review` 或者 `waiting-for-pr` 状态。计划在下周三完成第二章、第三章的翻译、合并工作。周三开始进入最后一章的翻译。

**Comment by rootsongjc** [comment]
已经基本翻译完成了，见：https://cloudnative.to/kubebuilder/

**Comment by majinghe** [comment]
已经翻译完毕，并向Kubebuilder官网提了issue <https://github.com/kubernetes-sigs/kubebuilder/issues/1651>，询问是否能够将中文文档merge到主库中。

**Comment by rootsongjc** [comment]
活动已结束，关闭 issue。
