### ISSUE TITLE
[直播] 2020.08.20，付业成，Go 夜读联合分享

### ISSUE THREAD

**Issue by stevensu1977** [cloudnativeto/community#25]
暂定时间: 
暂定内容:
   TiDB DaaS operator 实践

**Comment by Miss-you** [comment]
约时间：
主题：
嘉宾介绍：
演讲简介：
直播调试：
宣传文章：

**Comment by rootsongjc** [comment]
@lonng 这个时间有定下来吗？

**Comment by lonng** [comment]
@rootsongjc CNCF 后的第二周，应该是 8 月中旬，具体哪一天待定

**Comment by rootsongjc** [comment]
8 月 12 日或 13 日 @lonng  邀请 TiDB 的付业成参加分享，并邀请他加入云原生社区。

**Comment by lonng** [comment]
@rootsongjc 已邀请，和 Speaker 和 Go 夜读确认最终时间为 08/20 号。

**Comment by apigateway-demo** [comment]
话术：

为了方便社区推广您的直播分享，麻烦提供下如下信息：
分享主题：（分享主题用这个么？TiDB DaaS operator 实践）
嘉宾介绍：
分享简介：（如果有一篇文章用于宣传直播就更好了)
分享大纲：
听众收获：
以及您的靓照一张

**Comment by Miss-you** [comment]
分享主题：TiDB Operator 架构与实现
嘉宾介绍：付业成 / PingCAP Cloud 工程师, Kubernetes 项目维护者
分享简介：     TiDB Operator 是 Kubernetes 上的 TiDB 集群自动运维系统，提供包括部署、升级、扩缩容、备份恢复、配置变更的 TiDB 全生命周期管理。借助 TiDB Operator，TiDB 可以无缝运行在公有云或私有部署的 Kubernetes 集群上。      主要分享主要从源码介绍 TiDB Operator 中采用的 Kubernetes 扩展功能方案。并以 TiDB Operator 举例，介绍如何编写一个 Operator，帮助用户完成自动化运维操作。

分享大纲：

- TiDB Operator 简介 
- 扩展 Kubernetes 几种方式
- TiDB Operator 实现 
听众收获：

- 了解 Kubernetes 常用的几种功能扩展方案。CRD，Custom Controller，Scheduler Extender, Admission Hook 等。
- 了解 TiDB Operator 如何实现自动化运维、Kubernetes 控制器常用编程范式等。

**Comment by Miss-you** [comment]
回放链接
https://www.bilibili.com/video/BV1Zt4y1U74M/

**Comment by rootsongjc** [comment]
直播已完成，关闭 issue。
