### ISSUE TITLE
云原生每周要闻/点评 计划

### ISSUE THREAD

**Issue by stevensu1977** [cloudnativeto/community#26]
计划：
   当周轮值编辑负责选择要闻，   邀请嘉宾, 管委会, 志愿者做要闻点评

**Comment by rootsongjc** [comment]
该计划最好有一个负责人，可以由志愿者来担任。@cloudnativeto/volunteer

**Comment by rootsongjc** [comment]
与 https://github.com/cloudnativeto/community/issues/36 重复，关闭本 issue 。
