### ISSUE TITLE
关于社区会议的软件选择

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#3]
云原生社区管委会最初在举行社区会议的时候对比了腾讯会议、zoom、钉钉内置会议，最终选择了 zoom，不过最近在使用 zoom 时遇到了一些问题，比如：
- 会议异常中断
- 声音有时候断断续续听不清楚

但是对比了 [zoom](https://zoom.us/pricing) 和[腾讯会议](https://meeting.tencent.com/buy.html)的价格。

## Zoom

- 免费版：限时 40 分钟，人数上限
- 付费版：最低 14.99 美元/月（支持 100 人参会），如果按年购买只需 149.9 美元，我觉得可以考虑购买一个。
- 功能：功能最强大，最完善，国际上使用最多

## 腾讯会议

- 免费版：到疫情结束之前不限时，不限参会人数，疫情结束后将限时 45 分钟，最高支持 25 人参会
- 付费版：最低 99 元/月，限制 25 人，100 人的话，499 元。
- 功能：不支持录屏，这个是硬伤，这个功能在直播分享时要用到

## 投票

请在该 issue 中回复你支持的会议软件，投票截止到 2020 年 6 月 24 日晚 9 点。

## 结论

可以考虑购买美区的 zoom pro，只需 149.9美元每年。

**Comment by xiongjy2104** [comment]
考虑社区参与者的分布，我选zoom+1

**Comment by Miss-you** [comment]
腾讯会议+1
当前腾讯会议优势是使用方便以及免费，缺点是不支持录屏（价格问题后续会调整，因为当前完全免费，所以价格问题可以暂时忽略）
录屏的问题我咨询下腾讯会议团队的录屏功能规划

**Comment by rootsongjc** [comment]
腾讯会议估计要不了几个月也要开始限时先人数了，而且 99 元最低档还只能有最多 25 人参会，这个价格对比 zoom 没有竞争力。建议继续使用 zoom。

**Comment by Jeremy-boo** [comment]
zoom+1

**Comment by rootsongjc** [comment]
我们就暂定使用 zoom 了。
