### ISSUE TITLE
[大会] 2020.08.15，GIAC，深圳，云原生专场

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#30]
会议网站：http://giac.msup.com.cn/Giac/schedule/index
请大家关注8 月 15 日，深圳的全球互联网大会（GIAC），云原生专场见。
深圳的朋友可以约起来了。
云原生专场中的社区讲师：
- @wangfakang
- @malphi

**Comment by Miss-you** [comment]
![image](https://user-images.githubusercontent.com/3816205/89122804-ffff7400-d4fc-11ea-827c-61f72a83e4e8.png)

**Comment by Miss-you** [comment]
已经给钱，成本150，邮费25
待确定邮寄地点。

giac审核ok

易拉宝大小：80*200cm

**Comment by rootsongjc** [comment]
活动已结束，易拉宝在大会主办方那里寄存。
