### ISSUE TITLE
[活动] Kubernetes 源码研习社

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#34]
2020年07月25 日完成了项目表
- [项目表]( https://docs.qq.com/sheet/DR3l5U3lLdE9BYktY )
- [Kubernetes 源码研习社 kickoff ](https://docs.qq.com/doc/DYWN6cE55dXlNRnlR )，暂定 8 月 2 日星期天晚上，不会早于这一天 @Miss-you 

7 月 27 日周一，发布调查问卷，@gasxia 同时在公众号里发布，让研习社成员填写问卷。@rootsongjc

**Comment by Miss-you** [comment]
【腾讯文档】研习社事项跟踪
https://docs.qq.com/sheet/DR3l5U3lLdE9BYktY

**Comment by rootsongjc** [comment]
调查问卷已设置完成并发放，截至 2020年07月27日22:01:24 已收到 118 份问卷，浏览量 203，回收率 58%，平均完成时间 3 分 20 秒。研习社现有学员总数 280 人。

**Comment by rootsongjc** [comment]
## Kubernetes 源码研习社 kickoff

- 时间：北京时间 2020 年 8 月 4 日晚 9 点至 10 点
- 会议链接：https://us02web.zoom.us/j/88964428722 （请提前下载好 zoom）
- 会议文档：https://docs.qq.com/doc/DR1ptSVFvWE5kSUdx
- 注意：视频会录制后上传到 [B 站云原生社区](https://space.bilibili.com/515485124/)
- 主办方：云原生社区 https://cloudnative.to
- 主持人：Jimmy Song @rootsongjc 
- 特别嘉宾：郑东旭，《Kubernetes 源码剖析》作者
- 社长：厉辉/yousa，腾讯云工程师，Apache APISIX PMC @Miss-you

**Comment by rootsongjc** [comment]
关于该活动后续信息请关注 https://github.com/cloudnativeto/sig-k8s-source-code/issues/1
不再使用本 issue 追踪。
