### ISSUE TITLE
[活动] Cloud Native Virtual Summit China 2020 推广

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#35]
Cloud Native Virtual Summit China 2020将于 7 月 30 - 8 月 1 日在线上举行，云原生社区作为 CNCF中国的合作伙伴，参与了本次活动的推广。

## 公众号文章发布

 现在已经有 2 篇文章：
- 可观测性：7 月 27 日发布
- Service Mesh：7 月 28 日发布
- 扩展性（Operator）：差一篇投稿
以上两篇已通过 CNCF review @Matthew-Dong  提供 markdown 格式，并提供给 @rootsongjc 发布

## 同场活动微信群

创建三个新的微信群并设定群主（一个或多个）：
- 可观测性 @zhaoweiguo 
- Service Mesh： @GuangmingLuo 
- 扩展性（Operator） @gasxia 

### 群主的职责

- 负责微信群的维护，包括拉人，邀请对应主题的讲师进入微信群。
- 了解 Cloud native virtual summit china 2020 对应主题的所有 topic，引导群内讨论

## TODO

- [ ] 缺的那篇稿子
- [x] 微信群的建立 @rootsongjc 
- [ ] 已有的两篇稿件的 review
- [ ] 与 CNCF 的人员对接，确认微信群二维码的会在大会上透出 @Matthew-Dong

**Comment by GuangmingLuo** [comment]
【服务网格】相关文章已经发布：https://mp.weixin.qq.com/s/6nPG2u7Q5f2y-VZCTaZ9wA

**Comment by rootsongjc** [comment]
三个主题的微信群已创建完成，并发送给 CNCF 了。

**Comment by rootsongjc** [comment]
已结束。
