### ISSUE TITLE
云原生社区端午节祝福视频

### ISSUE THREAD

**Issue by lonng** [cloudnativeto/community#4]
趁此端午佳节来临之际，云原生社区要推出一个端午节祝福小视频。

## 目的

展示云原生社区朝气蓬勃的面貌，送出端午节祝福。

## 参加者

云原生社区管委会全体成员 @cloudnativeto/streering-commitee 及部分志愿者 @cloudnativeto/volunteer，只要你想发布祝福视频都可以参与。

## 要求

视频时长：每人的片段一般不超过 10 秒，总时长控制在 2 分钟左右。
视频技术要求：1080P 30 帧，横屏录制，采用同期声（非后期配音，因此请找一个安静的环境录制）请保持拍摄设备水平静止，不要晃动，人像居于中间。
着装要求：不允许穿着带有明显品牌商或者厂商 logo 的衣服（开源社区的文化衫除外）
语言：中英文皆可
话语格式：大家好，我是 xxx，祝大家 xxx。
截止提交时间：2020 年 6 月 24 日下午 6 点
发布时间：2020 年 6 月 25 日端午节当天
发布渠道：B 站、微信视频号
接收人：@rootsongjc
后期制作：@rootsongjc @shenhonglei

## 参考

请参考下面我拍摄的这个视频。在视频拍摄完成后请做一个挥手的动作，多个视频这样串起来。

https://share.weiyun.com/2nmo2qLv

**Comment by tristaZero** [comment]
Hi everyone, here is my video.

复制这段内容后打开百度网盘手机App，操作更方便哦
链接：https://pan.baidu.com/s/12uYxpEi2JEz9hDOqY9l_5Q 提取码：c508

**Comment by rootsongjc** [comment]
感谢 @tristaZero 的视频，截止到目前，已经收到 6 个视频了，大家加油啊！

**Comment by Miss-you** [comment]
已提交。不知道视频是否符合要求:P

**Comment by Matthew-Dong** [comment]
Uploaded to Google Drive. :)

**Comment by rootsongjc** [comment]
感谢大家的配合与支持，视频已发布到微信视频号「云原生社区」及 B 站平台，https://www.bilibili.com/video/BV1Sg4y1v7cn
