### ISSUE TITLE
[社区] 本地用户组

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#40]
西安、长沙等地已有成员希望成立云原生社区的本地化组织，关于这个问题会在本周的云原生社区的周会中讨论。

**Comment by qq1778551951** [comment]
支持，大力推广云原生，在国内各大城市布局

**Comment by chenpfeisoo** [comment]
本地化组织确实有很多好处：
1.方便社区成员交流，技术，方案，踩坑，心得，还可以扩大社区影响力
2.社区同学见面，了解，熟悉，方便社区沟通

**Comment by rootsongjc** [comment]
大家在回复时顺便说下在哪个城市，我们可以考虑发起几个本地社区。目前从社区成员分布来看，北京、广东、上海、浙江、四川的居多。

**Comment by rootsongjc** [comment]
@lonng 会跟进云原生社区城市站。

**Comment by jinrunsen** [comment]
坐标南京。  
曾经参与过一个华为云办的ServiceMesh线下会议，会后拉过一个群，我可以往群发一些通知，鼓励大家来参与线下MeetUp。

**Comment by lonng** [comment]
感谢 @gasxia 
好的，近两周我们会先在成都聚一下，后面再讨论一下其他城市怎么实施。

**Comment by qq1778551951** [comment]
坐标长沙，K8S集群稳定运行一年，积累了一些使用经验，热爱云原生，倡导云原生

**Comment by rootsongjc** [comment]
第一期线下的云原生社区 meetup 将会安排在北京，到时候会邀请北京的云原生大咖参与分享，现场参与也会有机会获得电子工业出版社赠书。具体时间待定。

**Comment by rootsongjc** [comment]
云原生社区深圳、成都站已在最近两个星期陆续成立，深圳站站长 @Miss-you，成都站站长 @lonng @stevensu1977

**Comment by rootsongjc** [comment]
本地用户组已由城市站计划取代，见 https://github.com/cloudnativeto/community/issues/50
