### ISSUE TITLE
[城市站]云原生社区上海站

### ISSUE THREAD

**Issue by sunny0826** [cloudnativeto/community#51]
#50 建立云原生社区上海站，由于人数超过 200 无法通过扫描群二维码加入，需添加站长 @sunny0826 郭旭东，添加请备注`云原生社区上海站-姓名-公司`，入群后请按照群公告修改昵称，谢谢。

<div align="center">
  <p>
<img src="https://user-images.githubusercontent.com/24563928/91013699-a29da500-e61a-11ea-9408-22d903ef7ab2.JPG" alt="郭旭东" width='350' />
  </p>
</div>

**Comment by rootsongjc** [comment]
[上海站](https://cloudnative.to/city/shanghai/)页面已上线，此 issue 已不再使用，关闭之。
