### ISSUE TITLE
[城市站]云原生社区杭州站

### ISSUE THREAD

**Issue by yangzdpssoft** [cloudnativeto/community#53]
#53 建立云原生社区杭州站，社区成员可以扫描如下二维码加入杭州站微信群

`构建一个开放、包容的交流环境，促进云原生技术的传播和普及`

![云原生社区杭州站](https://user-images.githubusercontent.com/2045284/91065669-5d519580-e663-11ea-9feb-be68df3fa172.jpg)

如果人数超过200或者二维码过期无法通过扫描加入，可添加站长 @yangzdpssoft 晓槐卩，或者直接添加微信号yangzdpssoft。

备注：**云原生社区杭州站**

![晓槐卩](https://user-images.githubusercontent.com/2045284/91065706-66dafd80-e663-11ea-9657-f49a3121c095.jpg)

**Comment by rootsongjc** [comment]
杭州站页面已上线，https://cloudnative.to/city/hangzhou/ 关闭该 issue。
