### ISSUE TITLE
[城市站]云原生社区成都站

### ISSUE THREAD

**Issue by lonng** [cloudnativeto/community#58]
#50 建立云原生社区成都，社区成员可以扫描如下二维码加入成都站微信群

<img src="https://user-images.githubusercontent.com/1638682/91116434-f4980680-e6be-11ea-9a1f-86e9fcbe50ee.png" width='350' />

如果人数超过200无法通过扫描加入，可添加站长 @lonng 龙恒，备注云原生社区成都站即可。

<img src="https://user-images.githubusercontent.com/1638682/91116471-04afe600-e6bf-11ea-997d-42626cd19c57.png" width='350' />

**Comment by rootsongjc** [comment]
成都站页面已更新，请访问 https://cloudnative.to/city/chengdu ，关闭该 issue。
