### ISSUE TITLE
[城市站]云原生社区大连站

### ISSUE THREAD

**Issue by dyingbleed** [cloudnativeto/community#62]
#50 建立云原生社区大连，社区成员可以扫描如下二维码加入大连站微信群

![WechatIMG72](https://user-images.githubusercontent.com/2310741/91161973-0947bf00-e6fe-11ea-807c-c8dc26b0fd18.jpeg)

如果人数超过200无法通过扫描加入，可添加站长 @dyingbleed Anthony，备注云原生社区大连站即可。

![WechatIMG73](https://user-images.githubusercontent.com/2310741/91162010-1664ae00-e6fe-11ea-82fa-bf858121d0af.jpeg)

**Comment by rootsongjc** [comment]
[大连站页面](https://cloudnative.to/city/dalian/)已上线，此 issue 已不再使用，关闭之。
