### ISSUE TITLE
[活动] Envoy 官方文档翻译

### ISSUE THREAD

**Issue by majinghe** [cloudnativeto/community#63]
Envoy 1.7 版本已经有中文翻译 <https://www.servicemesher.com/envoy>。如今Envoy已经更新到1.15+，应读者要求，云原生社区打算将中文翻译更新至最新版本。

**Comment by majinghe** [comment]
翻译的前期工作和 Kubebuilder https://github.com/cloudnativeto/community/issues/21 ，这次翻译需要召集更多的志愿者。

**Comment by rootsongjc** [comment]
本地翻译活动的 Owner 为 @lhb008

**Comment by Miss-you** [comment]
+1，带我一个，近期准备钻研envoy

**Comment by luffyao** [comment]
+1 报名

**Comment by webup** [comment]
+1

**Comment by hzliangbin** [comment]
+1

**Comment by majinghe** [comment]
这周开始前期准备工作，主要工作如下
- [x] Fork Envoy GitHub Repo 
- [x] 配置GitHub Repo CI 和mergify
- [x] 书写翻译指南
- [x] 发布翻译志愿者招募通告
- [x] 创建志愿者登记表以及追踪登记表
- [x] 创建翻译issue
- [x] 制定翻译计划

此次翻译由 我 张晓辉  许振文 一起负责。

**Comment by rootsongjc** [comment]
本活动已经正式开始了，关闭该议题。
