### ISSUE TITLE
[直播] 王夕宁，Istio

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#69]
9 月底或者十月初 @Miss-you

**Comment by Miss-you** [comment]
跟夕宁老师定的是9.24日晚上8-9点

**Comment by Miss-you** [comment]
约时间：9月24日晚上8-9点
主题：待定
讲师 
嘉宾介绍：Istio 大佬、阿里云服务网格负责人
演讲简介：待定
直播调试：待定
宣传文章：待定

**Comment by rootsongjc** [comment]
2020 年 9 月 24 日晚，直播结束，下一步需要：
- 剪辑直播时的视频并发布到 B 站
- 考虑下是否要整理文字稿？
@Miss-you

**Comment by rootsongjc** [comment]
活动已结束，关闭 issue。更多直播活动请关注云原生学院：https://github.com/cloudnativeto/academy
