### ISSUE TITLE
0622-0628 微信公众号发布安排

### ISSUE THREAD

**Issue by Matthew-Dong** [cloudnativeto/community#7]
时间 | 内容 | 内容负责人 | 内容提交 DDL
-- | -- | -- | --
6.25 11:00 | 端午祝福视频 | Jimmy | 6.24
6.26 11:00 | Kubernetes v1.17+ 集群下 CNI 使用 VXLAN 模式 SVC 有 63 秒延迟的触发原因定位 | Yitao | 6.25
6.27 11:00 | CNCWeekly No.1 | Wei Su | 6.26
6.27 11:00 | CNCF 虚拟峰会推广 | Yitao | 6.26

**Comment by rootsongjc** [comment]
发布时间需要修正下，端午节假期期间只发布视频即可。
