### ISSUE TITLE
[直播] 2020.10月中旬，apache puslar

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/community#72]
约时间：10月中旬
主题：待定
讲师 
嘉宾介绍：Apache Puslar Founder & VP.
演讲简介：待定
直播调试：待定
宣传文章：待定

**Comment by rootsongjc** [comment]
活动已结束，关闭 issue。更多直播活动请关注云原生学院：https://github.com/cloudnativeto/academy
