### ISSUE TITLE
[直播] 时间待定，蔡卫东，腾讯，Kubernetes扩展到无限

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/community#73]
约时间：待定
主题：待定
讲师 蔡卫东
嘉宾介绍：腾讯
演讲简介：待定
直播调试：待定
宣传文章：待定

**Comment by rootsongjc** [comment]
云原生学院直播不再此仓库追踪，请转至 https://github.com/cloudnativeto/academy
