### ISSUE TITLE
[直播] 时间待定，王冬，kubeedge，边缘计算

### ISSUE THREAD

**Issue by Miss-you** [cloudnativeto/community#76]
约时间：待定
主题：待定
讲师 待定
嘉宾介绍：待定
演讲简介：待定
直播调试：待定
宣传文章：待定

边缘计算中最大的问题是网络问题

**Comment by rootsongjc** [comment]
云原生学院直播不再此仓库追踪，请转至 https://github.com/cloudnativeto/academy
