### ISSUE TITLE
需要制作一个社区介绍的易拉宝

### ISSUE THREAD

**Issue by GuangmingLuo** [cloudnativeto/community#8]
易拉宝至少包含以下内容：

- 社区logo
- 社区介绍
- 社区官方公众号

**Comment by rootsongjc** [comment]
这个易拉宝将在各个会议现场展示。

**Comment by Miss-you** [comment]
我妹子刚好放暑假，我让她试试……
（真*全家老小做开源）

**Comment by rootsongjc** [comment]
@GuangmingLuo 有没有截止时间，什么时候要做好？易拉宝需要提供哪些内容有什么要求？

**Comment by Miss-you** [comment]
需要关心的事情：
1、易拉宝初稿
2、易拉宝打印价格

**Comment by Miss-you** [comment]
![image](https://user-images.githubusercontent.com/3816205/87170359-d25f4a80-c303-11ea-9335-f45454eb022f.png)

**Comment by Miss-you** [comment]
![image](https://user-images.githubusercontent.com/3816205/87170388-dc814900-c303-11ea-8bed-2236e72c3db0.png)

**Comment by Miss-you** [comment]
两张易拉宝，周六讨论下哪个更合适，哪些地方还需要改动

选择深蓝色的

**Comment by rootsongjc** [comment]
个人觉得那个蓝色底的更好看些，不过文字内容还需要再斟酌下。

**Comment by Miss-you** [comment]
易拉宝价格
易拉宝需要什么时候之前做好
易拉宝内容敲定
社区slogan

**Comment by Miss-you** [comment]
![image](https://user-images.githubusercontent.com/3816205/87574344-cf4bcc00-c700-11ea-94cc-cfbe80b414be.png)

**Comment by rootsongjc** [comment]
经过 7 月 18 日晚社区会议的讨论，社区介绍修改为以下文字：
云原生社区始于 2016 年成立的 Kubernetes & CloudNative 实战群，覆盖了上千名早期云原生拥护者。在此基础上于 2020 年 5 月，由 CNCF 大使、开源领域意见领袖共同发起将原社群升级为云原生社区，旨在构建一个开放、包容的沟通环境，促进云原生技术的传播和普及。

**Comment by Miss-you** [comment]
> 云原生社区始于 2016 年成立的 Kubernetes & CloudNative 实战群，覆盖了上千名早期云原生拥护者。在此基础上于 2020 年 5 月，由 CNCF 大使、开源领域意见领袖共同发起将原社群升级为云原生社区，旨在构建一个开放、包容的沟通环境，促进云原生技术的传播和普及。

shoudao

**Comment by Miss-you** [comment]
初稿版本
![image](https://user-images.githubusercontent.com/3816205/87930204-3af3b780-caba-11ea-87ae-57ba8ec4eedb.png)

**Comment by rootsongjc** [comment]
用来个 issue 来追踪有点麻烦，关闭这个，统一到 https://github.com/cloudnativeto/community/issues/23 讨论吧。
