### ISSUE TITLE
[日历] 制作一个 google calendar 用于订阅社区活动

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/community#85]
社区活动越来越频繁，为了便于大家安排时间，需要制作一个 Google calender 给大家订阅。

**Comment by rootsongjc** [comment]
社区共享日历订阅地址：https://calendar.google.com/calendar/u/0?cid=bHFzZ29yZG8wcXFxMzljbjBnczR2bHNmM3NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

## 如何订阅

在 Mac 的日历中可以直接使用上面的链接订阅。

![image](https://user-images.githubusercontent.com/3328185/93230791-a7cdba00-f7aa-11ea-8582-48894c5f041d.png)

**Comment by addozhang** [comment]
就我自己有问题么？浏览器打开ok

![image](https://user-images.githubusercontent.com/2224492/94214741-f72f8b00-ff0c-11ea-86f6-26360043ac28.png)

**Comment by rootsongjc** [comment]
维护成本太高，取消日历功能，有活动会在公众号中通知。
