### ISSUE TITLE
[线下聚会]云原生社区上海站线下聚会

### ISSUE THREAD

**Issue by sunny0826** [cloudnativeto/community#87]
时间：2020年10月08日
地点：葵音咖啡（徐汇区）
参与人员：上海站管委会成员
本次活动由 @sunny0826 组织，主要为确定**上海站 logo** 和上海站**宣传片**拍摄，以及讨论上海站**后续发展规划**。参与人员为上海站管委会成员，由于是初创，上海站管委会暂时由站长和5位社区积极分子组成，后续视情况发展核心成员。

**Comment by shenhonglei** [comment]
<img width="1666" alt="shanghai" src="https://user-images.githubusercontent.com/20896372/95462111-a8243400-09a9-11eb-96c8-cd351caa9259.png">

**Comment by sunny0826** [comment]
本次会议纪要：https://docs.qq.com/doc/DY1hKaVBneGlzdm1m?createTS=1602141058258&templateId=30030

**Comment by rootsongjc** [comment]
本次活动已结束，关闭 issue。上海站的后续活动请关注 repo 中的新 issue 通知。
