### ISSUE TITLE
[线下活动]上海1024极客文化节

### ISSUE THREAD

**Issue by sunny0826** [cloudnativeto/community#94]
本次活动由 @sunny0826 组织，从赞助商处获得了一些**1024极客文化节**门票，作为上海站福利免费发放给社区成员，同时也作为上海站成员首次线下面基活动。还未获得门票的同学可以在上海站微信群 @沈旭(@a-ethan) 老师，直接去现场取票。

时间：2020年10月23日
地点：上海杨浦区创智天地广场
参与人员：上海站成员
活动内容：社区成员线下面基、合影，上海站宣传片素材拍摄

**感谢 UCloud 的赞助**

**Comment by rootsongjc** [comment]
这是 UCloud 制作的本次活动的宣传海报。

![image](https://user-images.githubusercontent.com/3328185/96968772-07567c80-1544-11eb-8b48-740f786c55a1.png)

**Comment by rootsongjc** [comment]
活动已结束，照片已上传到[上海站页面](https://cloudnative.to/city/shanghai/)。
